act: SiLU
act_entropy: 0.0003
action_repeat: 4
actor_layers: 3
actor_max_std: 1.0
actor_min_std: 0.1
barlow_lambd: 0.0005
barlow_scale: 0.05
batch_length: 32
batch_size: 32
blocks: 8
buffer_max_size: 500000
cnn_depth: 16
cnn_kernel: 5
cnn_mults:
- 2
- 3
- 4
- 4
cont_layers: 1
cont_scale: 1.0
critic_layers: 3
deter: 2048
discrete: 16
dmc_task: CarRacing-v3
dyn_layers: 1
dyn_scale: 1.0
env_num: 4
eps: 1.0e-08
eval_episode_num: 10
grad_clip: 1000.0
hidden: 256
horizon: 333
imag_horizon: 8
img_layers: 2
kl_free: 1.0
lamb: 0.95
lr: 4.0e-05
obs_layers: 1
policy_scale: 1.0
rep_scale: 0.1
repval_scale: 0.3
reward_layers: 1
reward_scale: 1.0
size:
- 64
- 64
slow_target_fraction: 0.02
slow_target_update: 1
steps: inf
stoch: 32
time_limit: 10000
train_ratio: 512
unimix_ratio: 0.01
units: 256
value_scale: 1.0
warmup: 1000
